name: Auto merge staging into main

on:
  push:
    branches:
      - staging

permissions:
  contents: write
  pull-requests: write

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config user.name "jaspreet"
          git config user.email "jaspreet_sunny@yahoo.com"

      - name: Merge staging into main
        run: |
          git fetch origin
          git checkout main
          git merge origin/staging --no-edit
          git push origin main
